spring:
  jwt:
    secret: VeX1WIV6dN7q7D8lKezpqaepeJI6B5aaaaaaavvvsffffffffffff
  datasource:
    url: jdbc:postgresql://chaeki-db.cdir8zoxnjfw.ap-northeast-2.rds.amazonaws.com:5432/chaeki
    username: postgres
    password: chaeki9999
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      springframework:
        security: DEBUG

cloud:
  aws:
    s3:
      bucket: chaeki-bucket
    credentials:
      access-key: AKIAXNSHSGAW7CRH6TXU
      secret-key: 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
    region:
      static: ap-northeast-2
      auto: false
    stack:
      auto: false